### PR TITLE
fix: force cast await to proper type

### LINKED ISSUE #1207: Typing of `act` broken
## Describe the bug

The `act` function exported by `@testing-library/react-native` is always of type `(callback: () => void) => void`. However, the underlying function coming from react-test-renderer also has overloads for promises which are incorrectly suppressed.

This error in typing leads to linter errors when one tries to pass promise-returning callbacks to `act` or tries to await a promise-returning `act`.

## Expected behavior

The `act` function should have the same typing as the underlying function from react-test-renderer.

## Steps to Reproduce

The following snippet will produce linter errors such as [this one](https://typescript-eslint.io/rules/no-misused-promises/), depending on one's linter configuration.
```
import { act } from '@testing-library/react-native'

await act(async () => {
  await Promise.resolve();
});
```

## Versions

    @testing-library/react-native: ^11.3.0 => 11.3.0 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-test-renderer: ^18.2.0 => 18.2.0

### LINKED ISSUE #1276: Typescript act() got warning `'await' has no effect on the type of this expression.`
## Describe the bug

when i use act with typescript , got warning like 👇

image
image

## Steps to Reproduce

`@testing-library/react-native/build/act.d.ts`

```diff
declare global {
    var IS_REACT_ACT_ENVIRONMENT: boolean | undefined;
}
declare function setIsReactActEnvironment(isReactActEnvironment: boolean | undefined): void;
declare function getIsReactActEnvironment(): boolean | undefined;
- declare const act: (callback: () => void) => void;
+ declare const act: <T>(callback: () => T) => T;
export default act;
export { setIsReactActEnvironment as setReactActEnvironment, getIsReactActEnvironment, };

```

## Versions

image

### PR DESCRIPTION
**Pull request by mdjastrzebski**
### Summary

Resolve typing issues with `act` by allowing to invoke both `act()` and `await act()`. React `act` has uses function overloading which is hard to work with, so I've resorted to casting.

Dropping support for mock `act` and increasing peer dep req to [React 16.8](https://github.com/facebook/react/releases/tag/v16.8.0) (earliest version to expose act in Test Renderer). I think we can avoid calling this a breaking change, as we already specified minimal RN version of 0.59, which uses React 16.8.3 ([see here](https://docs.google.com/presentation/d/1Z8mNkRw5CJ93qSQqESrcXbgia1dA8V1olnpKT0lsygk/edit#slide=id.gdc26277501_0_39))

Resolves #1276 
Resolves #1207

### Test plan

Typecheck runs fine.

### CODE REVIEW

File: src/act.ts [hunk 1]
```diff
@@ -77,6 +74,14 @@ function withGlobalActEnvironment(actImplementation: Act) {
     }
   };
 }
+
+type MockAct = (callback: () => void) => void;
+type Act = typeof reactTestRendererAct extends undefined ? MockAct : ReactAct;
+
+const actMock = (callback: () => void) => {
```
Comment (mdjastrzebski) [inline src/act.ts:81]: @thymikee do we still need to mock `act` in case RTR does not expose it? Seems like it was added in 2019. https://github.com/facebook/react/commit/267ed981466ef323b1461b013b5db8db31e31772

Comment (thymikee) [reply src/act.ts:81]: Yeah let's drop it

Comment (mdjastrzebski) [reply src/act.ts]: Dropping support and increasing peer dep req to React 16.8 (earlierst version to expose `act` in Test Renderer). I think we can avoid calling this a breaking change, as we already specified minimal RN version of 0.59, which uses React 16.8.3 ([see here](https://docs.google.com/presentation/d/1Z8mNkRw5CJ93qSQqESrcXbgia1dA8V1olnpKT0lsygk/edit#slide=id.gdc26277501_0_39))

Comment (AugustinLF) [reply src/act.ts]: Sounds fair to me, I'd still suggest being explicit about it in the release notes!

File: src/__tests__/act.test.tsx [hunk 2]
```diff
@@ -43,7 +43,7 @@ test('fireEvent should trigger useState', () => {
 });
 
 test('should act even if there is no act in react-test-renderer', () => {
```
Comment (AugustinLF) [inline src/__tests__/act.test.tsx:45]: I'd assume this test is not needed anymore.

File: src/act.ts [hunk 3]
```diff
@@ -20,10 +18,8 @@ function getIsReactActEnvironment() {
   return globalThis.IS_REACT_ACT_ENVIRONMENT;
 }
 
-type Act = typeof reactTestRendererAct;
-
-function withGlobalActEnvironment(actImplementation: Act) {
-  return (callback: Parameters<Act>[0]) => {
+function withGlobalActEnvironment(actImplementation: ReactAct) {
```
Comment (AugustinLF) [inline src/act.ts:21]: Is it even useful to pass it `actImplementation` as a param?

Comment (mdjastrzebski) [reply src/act.ts:21]: hmmmm, good question, we've got our code from RTL and just sprinkled types and eslint ignores over it. 
I guess it's easier to keep it in sync with their implmentation.

File: src/__tests__/act.test.tsx (hunk 2 above)
Comment (mdjastrzebski) [reply src/__tests__/act.test.tsx]: Good catch, I've removed that tests. Funny thing is that it did not fail despite no longer supporting missing `act`.

**Review by AugustinLF — APPROVED** [review]

File: package.json [hunk 4]
```diff
@@ -60,7 +60,7 @@
     "jest": ">=28.0.0",
     "react": ">=16.0.0",
     "react-native": ">=0.59",
-    "react-test-renderer": ">=16.0.0"
+    "react-test-renderer": ">=16.8.0"
```
Comment (thymikee) [inline package.json:63]: hm, React and React Test Renderer should go in sync to avoid weird issues

**Review by thymikee — APPROVED** [review]
Left one comment, other than that LGTM

**Review by trajano — COMMENTED** [review]
lgtm
